# Generated by Django 3.1.1 on 2020-09-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='ActorName')),
                ('Year', models.IntegerField(verbose_name='YearOfBirth')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='FilmName')),
                ('Year', models.IntegerField(verbose_name='YearOfCreation')),
            ],
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actors.actor')),
                ('FilmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actors.film')),
            ],
        ),
    ]
