# Generated by Django 3.1.1 on 2020-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='Name',
        ),
        migrations.AddField(
            model_name='film',
            name='Poster',
            field=models.ImageField(default=2, upload_to='Films'),
            preserve_default=False,
        ),
    ]
