# Generated by Django 3.1.1 on 2020-09-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actors', '0002_auto_20200910_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='Year',
            new_name='actorYear',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Name',
            new_name='filmName',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Poster',
            new_name='filmPoster',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Year',
            new_name='filmYear',
        ),
    ]
