# Generated by Django 3.1.1 on 2020-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actors', '0004_auto_20200910_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actorName',
            field=models.CharField(default='default_name', max_length=200, verbose_name='ActorName'),
        ),
    ]
